defaults: &defaults
  app_name: Exams

development:
  <<: *defaults
  host: localhost:3000
  mails:
    noreply: noreply@flatsoft.com

test:
  <<: *defaults
  host: localhost:3000
  mails:
    noreply: noreply@flatsoft.com

production:
  <<: *defaults
  host: exams.flatsoft.com
  mails:
    noreply: noreply@flatsoft.com
