defaults: &defaults
  app_name: Exams

development:
  <<: *defaults
  host: localhost:3000
  mails:
    noreply: noreply@flatsourcing.com

test:
  <<: *defaults
  host: localhost:3000
  mails:
    noreply: noreply@flatsourcing.com

production:
  <<: *defaults
  host: exams.flatsourcing.com
  mails:
    noreply: noreply@flatsourcing.com
